# Generated by Django 5.1.4 on 2025-01-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categories_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='fk_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
    ]
