# Generated by Django 5.1.4 on 2025-01-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_fk_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='tagList',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
    ]
